sudo: required
language: node_js
services:
  - docker

before_install:
  - docker build -t marcelopereiranunes/docker-react -f Dockerfile.dev .

script:
  - docker run marcelopereiranunes/docker-react npm run test -- --coverage
