sudo: required
language: node_js
services:
  - docker

before_install:
  - docker build -t marcelopereiranunes/docker-react -f Dockerfile.dev .

script:
  - docker run marcelopereiranunes/docker-react npm run test-ci

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-861199463694"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
